### ISSUE TITLE
Connection pool exhausted after multiple failures

### ISSUE THREAD

**Issue by fabianishere** [atlarge-research/opendc-web-server#12]
Today I had to restart the opendc.org webserver, since we were unable to make any API request due to the database connection pool being exhausted:

```
 [2018-11-27 10:18:48,275] ERROR in app: Exception on /tokensignin [POST]
Traceback (most recent call last):
   File "/usr/local/lib/python2.7/dist-packages/Flask-1.0.2-py2.7.egg/flask/app.py", line 2292, in wsgi_app
     response = self.full_dispatch_request()
   File "/usr/local/lib/python2.7/dist-packages/Flask-1.0.2-py2.7.egg/flask/app.py", line 1815, in full_dispatch_request
     rv = self.handle_user_exception(e)
   File "/usr/local/lib/python2.7/dist-packages/Flask-1.0.2-py2.7.egg/flask/app.py", line 1718, in handle_user_exception
     reraise(exc_type, exc_value, tb)
   File "/usr/local/lib/python2.7/dist-packages/Flask-1.0.2-py2.7.egg/flask/app.py", line 1813, in full_dispatch_request
     rv = self.dispatch_request()
   File "/usr/local/lib/python2.7/dist-packages/Flask-1.0.2-py2.7.egg/flask/app.py", line 1799, in dispatch_request
     return self.view_functions[rule.endpoint](**req.view_args)
   File "opendc-web-server/main.py", line 69, in sign_in
     user = User.from_google_id(idinfo['sub'])
   File "/opendc/opendc-web-server/opendc/models/user.py", line 23, in from_google_id
     user = cls._from_database('SELECT * FROM users WHERE google_id = %s', (google_id,))
   File "/opendc/opendc-web-server/opendc/models/model.py", line 166, in _from_database
     model_from_database = database.fetchone(statement, values)
   File "/opendc/opendc-web-server/opendc/util/database.py", line 47, in fetchone
     connection = CONNECTION_POOL.get_connection()
   File "build/bdist.linux-x86_64/egg/mysql/connector/pooling.py", line 310, in get_connection
     "Failed getting connection; pool exhausted")
 PoolError: Failed getting connection; pool exhausted
```

This only occurred after several error responses (such as `OccupiedTilePosition`) and leads me to believe we are not properly returning connections to their pool after an error occurs.

**Comment by fabianishere** [comment]
I suspect the connection is not closed in case `cursor.execute` raises an exception:
https://github.com/atlarge-research/opendc-web-server/blob/39a147b14d9ad079433d5405c7a3d533851095fa/opendc/util/database.py#L26-L32

This needs to be wrapped in a context manager/try-finally block. What do you think @gandreadis?

**Comment by lfdversluis** [comment]
Or try, except, *finally*

**Comment by gandreadis** [comment]
@fabianishere I agree, good catch!

**Comment by leonoverweel** [comment]
Oops yeah, wrote this before I knew to use `with` for this kind of stuff 😅
