### ISSUE TITLE
`[Errno 32] Broken pipe` on early client disconnect

### ISSUE THREAD

**Issue by leonoverweel** [atlarge-research/opendc-web-server#3]
Sometimes the server throws the following stack trace:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/eventlet/wsgi.py", line 515, in handle_one_response
    write(b''.join(towrite))
  File "/usr/local/lib/python2.7/dist-packages/eventlet/wsgi.py", line 462, in write
    wfile.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
  File "/usr/local/lib/python2.7/dist-packages/eventlet/greenio/base.py", line 390, in sendall
    tail = self.send(data, flags)
  File "/usr/local/lib/python2.7/dist-packages/eventlet/greenio/base.py", line 384, in send
    return self._send_loop(self.fd.send, data, flags)
  File "/usr/local/lib/python2.7/dist-packages/eventlet/greenio/base.py", line 371, in _send_loop
    return send_method(data, *args)
error: [Errno 32] Broken pipe
```

Problem is probably a client disconnecting early, or the socket closing some other way. See http://stackoverflow.com/questions/11866792/how-to-prevent-errno-32-broken-pipe.

**Comment by ghost** [comment]
How are you @leonoverweel I am having the same issue here, did you fix it?

**Comment by leonoverweel** [comment]
@gandreadis any updates on this? IIRC we shelved this as being client-side last time it came up, but I'm not sure if we ever addressed it.

@annata83 can you post your full trace?
